require "user.colorscheme"
require "user.keymaps"
require "user.plugins"
require "user.options"
require "user.autopairs"
require "user.treesitter"
require "user.indentline"
require "user.nvimtree"
require "user.telescope"
require "user.colorizer"
-- require "user.jdtls"
require "user.lsp"
require "user.copilot"
require "user.cmp"
require "user.toggleterm"
require "user.smoothscrolling"
require "user.tabout"
require "user.renamer"
require "user.project"
-- require "user.debugger"
-- require "user.youcompleteme"
